### ISSUE TITLE
error for lu(A')

### ISSUE THREAD

**Issue by stevengj** [JuliaSparse/SuiteSparse.jl#35]
From [discourse](https://discourse.julialang.org/t/sparse-linear-alegbra-question-lu-sparsematrixcsc/62625), moved from https://github.com/JuliaLang/julia/issues/41154:
```jl
using LinearAlgebra, SparseArrays
A = sprand(10,10,0.5)
lu(A')
```
gives
```jl
ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64, Int64}, ::Val{true}; check=true)
Closest candidates are:
  lu!(::StridedMatrix{T}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:79
  lu!(::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S}, ::Union{Val{false}, Val{true}}; check) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:88
  lu!(::StridedMatrix{T} where T, ::Union{Val{false}, Val{true}}; check) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:130
```
@dkarrasch points out that there is no `lu!` for `SparseArrays`, so the fix here seems nontrivial.

One option is to simply throw a clearer error, suggesting that the caller consider `lu(A)'` instead.

**Comment by Wimmerer** [comment]
From the user guide it looks like it does. Let me look into this further.

**Comment by ViralBShah** [comment]
Even if we do a temporary fix where we compute the transpose and then do the `lu`.

**Comment by Wimmerer** [comment]
So UMFPACK can transpose A for us (or we can, either one). But we can solve any of the systems from page 26 of https://fossies.org/linux/SuiteSparse/UMFPACK/Doc/UMFPACK_UserGuide.pdf. That opens up a number of possibilities, and I'm not sure which is best.

**Comment by ViralBShah** [comment]
What do you recommend? 2 seems most natural

**Comment by Wimmerer** [comment]
2 seems like a good choice to avoid any magic behind the scenes. It does mean we materialize a second matrix which could be annoying in some cases. 4 avoids that but seems to magical.

I think for now I'll make a PR for 2, I don't think it would be breaking to switch behind the scenes later to something like 4. And instead I can just better expose the different solve types of UMFPACK here or in LinearSolve.

**Comment by ViralBShah** [comment]
Oh I thought UMFPACK could solve the transpose system as if it was materialized - that's what I thought 2 was about. If not, then just materialize the transpose right now. The copy is not a problem because sparse factorization often has huge fill-in anyways. I would first address the issue quickly in the easiest possible way.

**Comment by Wimmerer** [comment]
UMFPACK can solve `A^Tx = b`, but that isn't done in the `lu(A)` stage, it's done when we do `/` so I'd have to add a field to UMFPACKLU to keep track. And I worry about the `L` and `U` being technically wrong if the user just wants the factorization.
