### ISSUE TITLE
Remove globals in umfpack.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSparse/SuiteSparse.jl#52]
Remove global state in umfpack.jl to make the code thread-friendly as discussed here:

https://github.com/JuliaLang/SuiteSparse.jl/issues/43#issuecomment-944903169

Each `UMFPackLU` should have its own `control` field.

**Comment by Wimmerer** [comment]
Closed by https://github.com/JuliaSparse/SparseArrays.jl/pull/98
