### ISSUE TITLE
Unable to identify Julia command (if available) for sparse eigendecomposition

### ISSUE THREAD

**Issue by matteoettam09** [JuliaSparse/SuiteSparse.jl#66]
Hello,

 we are building on a Matlab code performing the eigendecomposition of a sparse matrix. Here is the command.

```matlab
[V,D] = eig(K,'nobalance');
```
The problem is we are aiming at using either Python or Julia, and we didn't manage to find a function returning the same eigenvectors (eigenvalues yes, for example with Octave wrapped in Python, but no eigenvectors). Is there something for us in this SuiteSparse.jl library?

Thank you,
Matteo

**Comment by Wimmerer** [comment]
Does [Arpack.jl](https://arpack.julialinearalgebra.org/stable/eigs/) have what you're looking for?

**Comment by Vishnu213** [comment]
Hi @Wimmerer , thanks for your suggestion. I used the Arpack package ("eigs()" command), but I am not getting the anticipated results. And, by using the command, F=eigen(A; permute=false ,scale=false,sortby=nothing), I am getting a result which is close to the Matlab command (eig(A, no balance)).  It would be really helpful if you can suggest any command that you know of in python (with "scale option") that is similar to "eigen" command of julia.
  Thank you very much

**Comment by DrTimothyAldenDavis** [comment]
I don't have any eigen solvers in SuiteSparse.  Just factorization methods, which are useful in eigenvalue solvers like ARPACK.
