### ISSUE TITLE
Move the tests also to SparseArrays

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSparse/SuiteSparse.jl#70]
@Wimmerer The tests should move to SparseArrays.jl as well.

**Comment by ViralBShah** [comment]
I believe @KristofferC is already looking into doing this.

**Comment by rayegun** [comment]
https://github.com/JuliaSparse/SparseArrays.jl/tree/main/test/solvers

Although I did accidentally remove the actual SparseArrays tests...

**Comment by KristofferC** [comment]
https://github.com/JuliaSparse/SuiteSparse.jl/tree/master/test

Should be removed then?

**Comment by rayegun** [comment]
I wasn't sure about that. Since we don't want to break compat of SuiteSparse I figured we'd keep the existing tests here *also*. That way nothing in this package breaks (not sure how that would happen though).

But it is a lot of duplicated loc.
